module.exports.legions = [
    'I Legion, Dark Angels',
    'III Legion, Emperor\'s Children',
    'IV Legion, Iron Warriors',
    'V Legion, White Scars',
    'VI Legion, Space Wolves',
    'VII Legion, Imperial Fists',
    'VIII Legion, Night Lords',
    'IX Legion, Blood Angels',
    'X Legion, Iron Hands',
    'XII Legion, World Eaters',
    'XIII Legion, Ultramarines',
    'XIV Legion, Death Guard',
    'XV Legion, Thousand Sons',
    'XVI Legion, Luna Wolves',
    'XVII Legion, Word Bearers',
    'XVIII Legion, Salamanders',
    'XIX Legion, Raven Guard',
    'XX Legion, Alpha Legion',
    'Knights-Errant',
    'Black Shields',
    'N/A - Non-Astartes'
]